Fixed the 3 issues in TorpedoStore
DinuBotan/ivt-lab pull request #3
Opened 2021-05-02 12:52 UTC by DinuBotan

2021-05-02 12:55 UTC, danilashtefan requested changes
Good job!

2021-05-02 12:55 UTC, danilashtefan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  Random generator = new Random();
Smart move

2021-05-02 12:55 UTC, danilashtefan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      this.torpedoCount -= numberOfTorpedos;
Great

2021-05-02 13:02 UTC, danilashtefan approved these changes

2021-05-02 13:02 UTC, merged

2021-05-19 06:41 UTC, micskeiz commented
Nice solution, clean repo!